### ISSUE TITLE
跑不起来~视频界面是空白的

### ISSUE THREAD

**Issue by pslxx** [JiangJuHong/FlutterQiniucloudLivePlugin#4]
相关日志
```
Creating a virtual display of size: [1080, 2340] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2259].
```

```
D/mali_winsys( 8822): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/flutter ( 8822): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Only support 16:9/4:3 ratio!, null)
E/flutter ( 8822): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 8822): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 8822): <asynchronous suspension>
E/flutter ( 8822): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter ( 8822): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter ( 8822): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter ( 8822): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter ( 8822): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter ( 8822): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter ( 8822): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #11     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter ( 8822): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter ( 8822): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #15     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter ( 8822): #16     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter ( 8822): #17     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter ( 8822): #18     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter ( 8822): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #23     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter ( 8822): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #39     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3166:14)
E/flutter ( 8822): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #41     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter ( 8822): #42     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter ( 8822): #43     PipelineOwner.flushLayout (package:flutter/sr
E/flutter ( 8822): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'addRemoteWindow' was called on null.
E/flutter ( 8822): Receiver: null
E/flutter ( 8822): Tried calling: addRemoteWindow(id: 1)
E/flutter ( 8822): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 8822): #1      PushPageState.onPlayerViewCreated (package:flutter_qiniucloud_live_plugin_example/page/push.dart:269:16)
E/flutter ( 8822): #2      QiniucloudConnectPlayerViewState._onPlatformViewCreated (package:flutter_qiniucloud_live_plugin/view/qiniucloud_connected_player_view.dart:44:14)
E/flutter ( 8822): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:643:15)
E/flutter ( 8822): <asynchronous suspension>
E/flutter ( 8822): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter ( 8822): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter ( 8822): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter ( 8822): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter ( 8822): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter ( 8822): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:544:15)
E/flutter ( 8822): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #14     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter ( 8822): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter ( 8822): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #18     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter ( 8822): #19     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter ( 8822): #20     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter ( 8822): #21     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter ( 8822): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #26     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter ( 8822): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8822): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 8822): #42     RenderOffstage.p
I/flutter ( 8822): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8822): The following NoSuchMethodError was thrown during paint():
I/flutter ( 8822): The getter 'width' was called on null.
I/flutter ( 8822): Receiver: null
I/flutter ( 8822): Tried calling: width
I/flutter ( 8822): 
I/flutter ( 8822): The relevant error-causing widget was:
I/flutter ( 8822):   AndroidView
I/flutter ( 8822):   file:///Users/tuobaye/Workspace/android/FlutterQiniucloudLivePlugin/lib/view/qiniucloud_connected_player_view.dart:27:14
I/flutter ( 8822): 
I/flutter ( 8822): When the exception was thrown, this was the stack:
I/flutter ( 8822): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 8822): #1      RenderAndroidView.paint (package:flutter/src/rendering/platform_view.dart:192:46)
I/flutter ( 8822): #2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #3      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 8822): #4      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 8822): #5      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter ( 8822): #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter ( 8822): #7      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #13     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter ( 8822): #14     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:589:5)
I/flutter ( 8822): #15     RenderStack.paint (package:flutter/src/rendering/stack.dart:597:7)
I/flutter ( 8822): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #21     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter ( 8822): #22     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:589:5)
I/flutter ( 8822): #23     RenderStack.paint (package:flutter/src/rendering/stack.dart:597:7)
I/flutter ( 8822): #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #26     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter ( 8822): #27     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:396:5)
I/flutter ( 8822): #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #31     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:530:11)
I/flutter ( 8822): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #35     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter ( 8822): #36     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1755:15)
I/flutter ( 8822): #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #42     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #44     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 8822): #45     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 8822): #46     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter ( 8822): #47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter ( 8822): #48     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #51     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #52     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter ( 8822): #53     PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:569:5)
I/flutter ( 8822): #54     RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:923:23)
I/flutter ( 8822): #55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #57     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #58     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2462:13)
I/flutter ( 8822): #59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #61     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #63     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 8822): #64     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 8822): #65     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter ( 8822): #66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter ( 8822): #67     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #71     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3181:11)
I/flutter ( 8822): #72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #73     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #74     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter ( 8822): #75     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:589:5)
I/flutter ( 8822): #76     RenderStack.paint (package:flutter/src/rendering/stack.dart:597:7)
I/flutter ( 8822): #77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #78     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #79     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #82     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #84     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #85     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #89     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #90     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #91     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #92     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:575:11)
I/flutter ( 8822): #93     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #95     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #96     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #97     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #98     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 8822): #99     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #100    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 8822): #101    RenderView.paint (package:flutter/src/rendering/view.dart:213:15)
I/flutter ( 8822): #102    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter ( 8822): #103    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 8822): #104    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 8822): #105    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:937:29)
I/flutter ( 8822): #106    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 8822): #107    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
I/flutter ( 8822): #108    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter ( 8822): #109    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter ( 8822): #110    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter ( 8822): #111    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter ( 8822): #115    _invoke (dart:ui/hooks.dart:259:10)
I/flutter ( 8822): #116    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter ( 8822): (elided 3 frames from package dart:async)
I/flutter ( 8822): 
I/flutter ( 8822): The following RenderObject was being processed when the exception was fired: RenderAndroidView#b1935:
I/flutter ( 8822):   needs compositing
I/flutter ( 8822):   creator: _AndroidPlatformView ← Semantics ← _FocusMarker ← Focus ← AndroidView ←
I/flutter ( 8822):     QiniucloudConnectPlayerView ← ConstrainedBox ← Container ← Positioned ← Stack ← ConstrainedBox ←
I/flutter ( 8822):     Container ← ⋯
I/flutter ( 8822):   parentData: <none> (can use size)
I/flutter ( 8822):   constraints: BoxConstraints(w=100.0, h=100.0)
I/flutter ( 8822):   layer: OffsetLayer#6b0d3 DETACHED
I/flutter ( 8822):   semantic boundary
I/flutter ( 8822):   size: Size(100.0, 100.0)
I/flutter ( 8822): This RenderObject has no descendants.
I/flutter ( 8822): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/AwareBitmapCacher( 8822): init lrucache size: 2097152 pid=8822
```

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The getter 'width' was called on null.
Receiver: null
Tried calling: width

The relevant error-causing widget was: 
  AndroidView file:///Users/tuobaye/Workspace/android/FlutterQiniucloudLivePlugin/lib/view/qiniucloud_connected_player_view.dart:27:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderAndroidView.paint (package:flutter/src/rendering/platform_view.dart:192:46)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
#3      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
#4      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
...
The following RenderObject was being processed when the exception was fired: RenderAndroidView#b1935
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=100.0, h=100.0)
...  layer: OffsetLayer#6b0d3
...    offset: Offset(260.0, 0.0)
...  semantic boundary
...  size: Size(100.0, 100.0)
RenderObject: RenderAndroidView#b1935
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=100.0, h=100.0)
  layer: OffsetLayer#6b0d3
    offset: Offset(260.0, 0.0)
  semantic boundary
  size: Size(100.0, 100.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)

```

**Comment by JiangJuHong** [comment]
发现错误提示信息，关键提示代码为：
```
I/flutter ( 8822): The following RenderObject was being processed when the exception was fired: RenderAndroidView#b1935:
I/flutter ( 8822):   needs compositing
I/flutter ( 8822):   creator: _AndroidPlatformView ← Semantics ← _FocusMarker ← Focus ← AndroidView ←
I/flutter ( 8822):     QiniucloudConnectPlayerView ← ConstrainedBox ← Container ← Positioned ← Stack ← ConstrainedBox ←
I/flutter ( 8822):     Container ← ⋯
```
可能考虑到的原因是Flutter嵌套出现问题，你是通过 example 运行还是在自有项目运行？能否提供更加详细描述

**Comment by pslxx** [comment]
都试了,,,
第一次是我自己复制你的代码,到我们项目不行,然后整个仓库clone下去,也是一样的
我后来在QiniucloudPushPlatformView 里面加上

```
 streamingProfile.setPreferredVideoEncodingSize(1200,900);
```
可以显示画面了,但是设置了之后,变焦有问题...然后我放弃了这个插件.准备用腾讯云的

**Comment by JiangJuHong** [comment]
感谢你的支持，如果有好的建议，欢迎提出。

**Comment by pslxx** [comment]
我的想法是把腾讯云的推流 SDK,单独拿来出封装
不跟整个腾讯云关联起来.我这边就是想做秀场直播,或者手机游戏直播,需要一个推流的SDK,包括摄像头画面捕捉,切换摄像头 闪光灯 暂停画面,弱网通知,推流事件回调,以及基本的美颜和滤镜功能,
因为腾讯云的SDK 推流地址是可以额外定义的,这样,我后端可以用七牛云,阿里云,或者自建ffmpeg服务器都可以.至于房间 IM 这些东西,都是自己后台的逻辑,不用腾讯云的

**Comment by pslxx** [comment]
所有我之前有考虑用您封装的TRCT ,但是这个东西有点多,封装的太多了,目前还在抉择中

**Comment by JiangJuHong** [comment]
这是一个不错的想法，但是现在 TencentRTC 这个插件的定义是基于TencentRTC SDK，所以功能也会更加偏向与此。我对你的这个想法表示感兴趣，但是现在暂时抽不出身，在有时间后我会考虑这个项目的可实现方案，如果可以，我们也可以进行更多的讨论。
